# bash/.pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt (write)
        language: system
        entry: shfmt -w -i 2 -ci
        types: [shell]
        require_serial: true
